// This file defines the Product class, which represents a product in the system.

namespace FASCloset.Models
{
    /// <summary>
    /// Represents a product in the inventory system
    /// Contains all product details including pricing, stock levels, and relationships to categories and manufacturers
    /// </summary>
    public class Product
    {
        /// <summary>
        /// Unique identifier for the product
        /// </summary>
        public int ProductID { get; set; }

        /// <summary>
        /// The name of the product
        /// </summary>
        public string ProductName { get; set; } = string.Empty;

        /// <summary>
        /// Foreign key to the Category table
        /// </summary>
        public int CategoryID { get; set; }

        /// <summary>
        /// Optional foreign key to the Manufacturer table
        /// </summary>
        public int? ManufacturerID { get; set; }

        /// <summary>
        /// Retail price of the product
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// Current quantity in inventory
        /// </summary>
        public int Stock { get; set; }

        /// <summary>
        /// Detailed description of the product
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Indicates whether the product is active and available for sale
        /// </summary>
        public bool IsActive { get; set; } = true;
        
        /// <summary>
        /// Navigation property: Name of the category this product belongs to (not stored in database)
        /// </summary>
        public string CategoryName { get; set; } = string.Empty;

        /// <summary>
        /// Navigation property: Name of the manufacturer for this product (not stored in database)
        /// </summary>
        public string ManufacturerName { get; set; } = string.Empty;
        
        /// <summary>
        /// Calculated property that indicates if stock is below minimum threshold
        /// </summary>
        public bool IsLowStock { get; set; }
        
        /// <summary>
        /// Number of times this product has been sold (for reporting)
        /// </summary>
        public int SalesCount { get; set; }

        /// <summary>
        /// Total quantity of this product sold (for reporting)
        /// </summary>
        public int TotalQuantity { get; set; }

        /// <summary>
        /// Total revenue generated by this product (for reporting)
        /// </summary>
        public decimal Revenue { get; set; }
        
        /// <summary>
        /// Quantity of this product in a specific order
        /// </summary>
        public int OrderQuantity { get; set; }

        /// <summary>
        /// Unit price of this product in a specific order (may differ from current Price)
        /// </summary>
        public decimal OrderUnitPrice { get; set; }

        /// <summary>
        /// Minimum stock level before notifications are triggered
        /// </summary>
        public int MinimumStockThreshold { get; set; } = 5;

        /// <summary>
        /// Formatted string displaying product name, price and stock level
        /// </summary>
        public string DisplayName => $"{ProductName} - {Price:C} - Stock: {Stock}";
        
        /// <summary>
        /// Property alias for ProductID (for compatibility with generic interfaces)
        /// </summary>
        public int Id { get => ProductID; set => ProductID = value; }

        /// <summary>
        /// Property alias for ProductName (for compatibility with generic interfaces)
        /// </summary>
        public string Name { get => ProductName; set => ProductName = value; }

        /// <summary>
        /// Property alias for CategoryID (for consistency with code conventions)
        /// </summary>
        public int CategoryId { get => CategoryID; set => CategoryID = value; }

        /// <summary>
        /// Property alias for ManufacturerID (for consistency with code conventions)
        /// </summary>
        public int? ManufacturerId { get => ManufacturerID; set => ManufacturerID = value; }
    }
}
